[package]
name = "musium"
version = "0.1.0"
authors = ["Will Cassella <wcassella@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
id3 = "0.5.1"
metaflac = "0.2"
tree_magic = "0.2.3"
